name: Build and Release

permissions:
  contents: write

on:
  [push]

jobs:

  build:

    runs-on: windows-2022

    env:
      Solution_Name: TEditor.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Release
        
    - name: Build App
      run: msbuild $env:Solution_Name /p:Configuration=Release
        
    - name: Upload net472 build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: net472
        path: TEditor\bin\Release\net472
        
    - name: Upload net6.0 build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: net6
        path: TEditor\bin\Release\net6.0-windows
        
    - name: Prepare release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        mv TEditor\bin\Release\net472\TEditor.exe TEditor-net472-${{ github.ref_name }}.exe
    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: y
        files: |
          TEditor-net472-${{ github.ref_name }}.exe
